# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-30 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_brand_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='num',
        ),
    ]
